# Generated by Django 4.2.10 on 2024-02-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('code', models.CharField(max_length=4)),
                ('duration', models.IntegerField()),
                ('modality', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.ManyToManyField(blank=True, related_name='students', to='users.career'),
        ),
    ]
