# Generated by Django 4.2.10 on 2024-02-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_modality_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('capacity', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salones',
            },
        ),
    ]
