# Generated by Django 4.2.10 on 2024-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_semester_alter_lounge_capacity_matter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matter',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Semestre', 'verbose_name_plural': 'Semestre'},
        ),
        migrations.AlterField(
            model_name='matter',
            name='credits',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='credits',
            field=models.IntegerField(),
        ),
    ]
